### ISSUE TITLE
Issues accessing the emulated TWC3 web server

### ISSUE THREAD

**Issue by cpflueger2016** [Haveacry/twc3teslamate#2]
Hey @speedst3r,

first of all, thanks for that code. I also have a Tesla UMC which I use for all my charging purposes. however, out of the box, it doesn't allow me to use EVCC. 

I have cloned your repo, built the docker image and I'm running it in my TeslaMate docker compose that runs within a Debian VM. When I run docker logs, I can see encouraging messages:

`docker logs teslamate-twc3teslamate-1` 

> Connected with result code Success

> INFO:     Started server process [1]
> INFO:     Waiting for application startup.
> INFO:     Application startup complete.
> INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)

However, no matter what IP address I'm using, I cannot access:

`http://IP_ADDRESS/api/1/vitals`

How would I reach the emulated TWC3 and what did you add in your EVCC config to make it work? 

Thanks heaps in advance!

**Comment by speedst3r** [comment]
> How would I reach the emulated TWC3

I couldn't comment because I don't know your setup - though it should be available on the host's IP address if you forwarded port 80 with your docker command. Or if you `docker inspect` the container you could try the container's IP while on the host.

> what did you add in your EVCC config to make it work?

I use kubernetes, but it should not be any different, I specified the IP of the twc3teslamate instance. But because I use kubernetes, the kubernetes service that makes the website available has a fixed IP, so I am able to just use that.

**Comment by cpflueger2016** [comment]
Ahhh, I think I get it. I'm somewhat new to docker containers so please bear with me. 
You're tip on looking at the `docker inspect` was super helpful. 
I can see that http://172.18.0.6/api/1/vitals returns the correct values from Teslamate. 

My current setup runs TeslaMate and `twc3teslamate` in the same Docker environment. That works well since twc3teslamate can easily query Mosquitto. I have included 

> ports: 
>   - 80:80 

in my docker-compose. I have home-assistant running on a different virtual machine. So essentially, I need to be able to point to the virtual machine that's running teslamate and twc3teslamate which would be 192.168.68.80. It works well for Teslamate and grafana (port 4000 and 3000) but I'm having trouble getting to twc3teslamate's output. Do you have an idea of the port configuration that I could try?

**Comment by speedst3r** [comment]
You could try forwarding another port, e.g. -p 3080:80 and then it would show up on your docker host on port 3080.

Closing this now as it is not an issue with the app itself.
