### ISSUE TITLE
Did not receive any information

### ISSUE THREAD

**Issue by 1990marco1990** [Haveacry/twc3teslamate#4]
It works if i go to the page but the information did not update. Teslamate and MQTT works.

INFO:     192.168.31.243:42874 - "GET /api/1/vitals HTTP/1.1" 200 OK

That is only the log of it in Portainer in Homeassistant

If i go to the http://192.168.31.243/api/1/vitals it show me something but ist not right.

[lp-1  ] ERROR 2024/08/06 12:19:01 charger status: Get "http://192.168.31.243:80/api/1/vitals": dial tcp 192.168.31.243:80: connect: connection refused

Thats the log from EVCC.

**Comment by speedst3r** [comment]
It seems like there are a couple of different issues here, likely configuration related.

1. If i go to the http://192.168.31.243/api/1/vitals it show me something but ist not right.
2. dial tcp 192.168.31.243:80: connect: connection refused

Let's start with 1 - what is not right with the interface?

**Comment by 1990marco1990** [comment]
The Interface show everything but If i load the Car It did not received any Data from the Car.

The logs also say that al right with MQTT but no Data there.

**Comment by speedst3r** [comment]
What environment variables have you set for the container? Is it using the same MQTT server as Teslamate?

**Comment by 1990marco1990** [comment]
version: '3.7'

services:
  twc3teslamate:
    image: dbzman/twc3teslamate
    container_name: twc3teslamate
    restart: unless-stopped
    network_mode: "host"  # Verwenden des host-Netzwerkmodus
    environment:
      - MQTT_HOST=192.168.31.243
      - MQTT_USERNAME=****
      - MQTT_PASSWORD=****
      - TWC_HOST=192.168.31.243
      - TWC_PORT=80

Yes its all in Homeassistent. Portainer,MQTT and Teslamate.

Teslamate Is ok If i Look with MQTT Explorer.

**Comment by speedst3r** [comment]
Do you have a Geofence area in Teslamate named "Home"? This is what the app uses to determine whether to update or not (along with whether the car is plugged in and charging):
https://github.com/Haveacry/twc3teslamate/blob/4605dde35f5c9cc76b89b04a0dcfefb64a2de5ed/app/main.py#L210
If your home location is named something else, you should supply it with the environment variable `TESLAMATE_GEO_HOME`. 

Without checking that the car is in the home location, the app would update if you plugged your car in elsewhere (e.g. public charger) and EVCC would then try to control charging.

`TWC_HOST` and `TWC_PORT` are not variables used by the app.

**Comment by 1990marco1990** [comment]
<html><body>

contactor_closed | false
-- | --
vehicle_connected | false
session_s | 0
grid_v | 0
grid_hz | 49.828
vehicle_current_a | 0
currentA_a | 0
currentB_a | 0
currentC_a | 0
currentN_a | 0
voltageA_v | 0
voltageB_v | 0
voltageC_v | 0
relay_coil_v | 11.9
pcba_temp_c | 7.4
handle_temp_c | 1.8
mcu_temp_c | 0
uptime_s | 26103
input_thermopile_uv | -176
prox_v | 0
pilot_high_v | 11.9
pilot_low_v | 11.8
session_energy_wh | 0
config_status | 5
evse_state | 1
current_alerts | []


</body>
</html>


Yes I have Home but the Data did not update.The Model Y say "nicht verbunden" in EVCC. I load it in the Home area.

Logs EVCC:

[lp-1  ] INFO 2024/08/07 09:32:49 vehicle updated: Model Y -> unknown
[lp-1  ] INFO 2024/08/07 09:32:52 vehicle updated: unknown -> Model Y


evccyaml:

mqtt:
  broker: 192.168.31.243:1883  # MQTT Broker Adresse
  user: ***
  password: ***

meters:
  - name: haus
    type: template
    template: shelly-3em
    usage: grid
    host: 192.168.31.166  # IP-Adresse oder Hostname
chargers:
  - name: charger
    type: template
    template: twc3
    host: 192.168.31.243:80
loadpoints:
  - title: Tesla Ladestation # Titel des Ladepunk
    charger: charger
    phases: 3  # Anzahl der Phasen für das Laden
    mode: pv  # Lademodus, der nur bei PV-Überschuss lädt
    minCurrent: 1  # Minimale Stromstärke pro Phase
    maxCurrent: 16  # Maximale Stromstärke pro Phase

**Comment by speedst3r** [comment]
Is there any output in the twc3teslamate container? It should at least output if it was able to connect to MQTT.

Otherwise I don't have any other suggestions than something specific to your setup.

**Comment by 1990marco1990** [comment]
INFO:     192.168.31.243:33306 - "GET /api/1/vitals HTTP/1.1" 200 OK
INFO:     192.168.31.243:50706 - "GET /api/1/vitals HTTP/1.1" 200 OK
INFO:     192.168.31.243:39930 - "GET /api/1/vitals HTTP/1.1" 200 OK
INFO:     192.168.31.243:44930 - "GET /api/1/vitals HTTP/1.1" 200 OK
INFO:     192.168.31.243:44930 - "GET /api/1/vitals HTTP/1.1" 200 OK
INFO:     192.168.31.243:51282 - "GET /api/1/vitals HTTP/1.1" 200 OK


Thats the log of the Container on portainer.

Its looks ok?
 

I can see the teslamate in MQTT Explorer but the twc3teslamate not. Is that ok?

**Comment by speedst3r** [comment]
> Its looks ok?

No, there should be output on success/failure of connection to MQTT.

https://github.com/Haveacry/twc3teslamate/blob/main/app%2Fmain.py#L84

>I can see the teslamate in MQTT Explorer but the twc3teslamate not. Is that ok?

Not sure I understand. Twc3teslamate will not create any topics on the MQTT server, only read the teslamate topics. The only relevant information will be the MQTT server logs where you can verify that twc3teslamate is connecting successfully.

**Comment by 1990marco1990** [comment]
INFO:     Application shutdown complete.
INFO:     Finished server process [1]
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
Connected with result code Success
INFO:     192.168.31.243:45610 - "GET /api/1/vitals HTTP/1.1" 200 OK
INFO:     192.168.31.243:58594 - "GET /api/1/vitals HTTP/1.1" 200 OK


Thats ok with Code success? I have restart it.

**Comment by speedst3r** [comment]
Looks right. I can't explain why it isn't working for you - is your car ID in Teslamate `1` ? I since changed to a Wallbox but ran a container again now and it is working for me. If it is connecting successfully to MQTT then it must not be subscribing to the correct topic?

`docker run -d --name twc3teslamate -p 8080:80 -e MQTT_HOST=192.168.0.XXX -e MQTT_USERNAME=twc3teslamate -e MQTT_PASSWORD=***** ghcr.io/haveacry/twc3teslamate`

That worked for me with my MQTT server in Home Assistant.

**Comment by 1990marco1990** [comment]
teslamate
teslamodely
cars
1
charge_current_request = 5
active_route_longitude = nil
tpms_pressure_fl = 2.975
sentry_mode = false
exterior_color = SolidBlack
tpms_soft_warning_fl = false
is_user_present = false
battery_level = 89
trunk_open = false
active_route_latitude = nil
model = Y
climate_keeper_mode = off
plugged_in = true
inside_temp = 36.9
version = 2024.20.9
charge_energy_added = 9.68
location = {"latitude":***,"longitude":***}
is_preconditioning = false
usable_battery_level = 89
time_to_full_charge = 0.0
est_battery_range_km = 379.11
tpms_soft_warning_rl = false
locked = true
rated_battery_range_km = 360.65
ideal_battery_range_km = 360.65
tpms_pressure_rl = 3.425
heading = 354
active_route_destination = nil
active_route = {"error":"No active route available"}
power = 0
tpms_pressure_rr = 3.45
geofence = Home
tpms_soft_warning_rr = false
driver_rear_door_open = false
tpms_pressure_fr = 2.975
frunk_open = false
spoiler_type = None
driver_front_door_open = false
trim_badging = 50
passenger_rear_door_open = false
tpms_soft_warning_fr = false
odometer = 14694.19
latitude = ****
charge_port_door_open = true
is_climate_on = false
charging_state = Stopped
windows_open = false
passenger_front_door_open = false
healthy = true
since = 2024-08-07T10:28:48.762591Z
charge_limit_soc = 100
state = suspended
doors_open = false
wheel_type = Apollo19
update_available = false
charge_current_request_max = 16
longitude = ****
center_display_state = 0
outside_temp = 26.5
speed = 0
elevation = 36
charger_voltage = 2
charger_actual_current = 0
charger_power = 0
charger_phases = 2

That is in teslamate. Its under teslamodely---cars---1  Its ok?

**Comment by 1990marco1990** [comment]
I I change to "ghcr.io/haveacry/twc3teslamate" the http://192.168.31.243/api/1/vital say 

<html><body>

detail | "Not Found"
-- | --



</body>
</html>

so I think the car did not find in teslamate?




I had a namespace in teslamate (teslamodely) I have delete it but also no information.

teslamate/cars/1/charger_voltage

Thats the new topic it is ok?

**Comment by speedst3r** [comment]
Yes, the topic the script subscribes to is `teslamate/cars/<car ID>/#`

**Comment by 1990marco1990** [comment]
Now it works. Thanks for your help.

EVCC does need a sponsoring its ok but I can not test if its work befor. The loading shows but nothing do if I change the mod.

**Comment by speedst3r** [comment]
https://github.com/Haveacry/twc3teslamate/commit/cd6ef5fdee1ed1bf7daccabc6ec8627654acb2b5 adds support for namespaces. Latest container builds should include this support.
