### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by balgerion** [Haveacry/twc3teslamate#5]
twc3teslamate is running on the same docker as evcc and teslamate
ENV:
192.168.1.65 is portainer srv (hosted EVCC, Teslamate and twc3)
192.168.1.101 MQTT broker on Home Assistant

MQTT Broker is on HA (EVCC and teslamate is connected without issue)
![{4C5685ED-3FDB-4D02-8BCD-7DEC2A2BCA05}](https://github.com/user-attachments/assets/c098cf92-b883-4604-9a75-1a9ee1a6f44e)

Stack config:
services:
  twc3teslamate:
   container_name: twc3teslamate
   image: ghcr.io/haveacry/twc3teslamate
   environment:
    - MQTT_HOST=192.168.1.101
    - MQTT_USERNAME=xxxxx
    - MQTT_PASSWORD=xxxxx
   restart: unless-stopped

Logs:
![{C64E0BDD-EB1A-4B09-AA01-512A123767F4}](https://github.com/user-attachments/assets/e791fe95-299c-42aa-8540-bd15bafd6655)

Error in EVCC  - empty page http://192.168.1.65/api/1/vitals 
![{CD062564-7E98-4D52-A991-ACE0D217A01F}](https://github.com/user-attachments/assets/2b4d589d-e26b-41c0-8688-13b2fc78a681)

im runnig out of idea how to troubleshoot that

**Comment by speedst3r** [comment]
Have you forwarded port 80 or another port to twc3teslamate?

**Comment by balgerion** [comment]
F*** Thank you! :D that was it!

**Comment by balgerion** [comment]
btw is this a bug ? or intended
![{E2625A14-3DE5-4F2A-B6B1-69D906FB8154}](https://github.com/user-attachments/assets/ce07d121-6a0e-474c-a782-91b10c54e787)

charging below 5a minimum is working from evcc  , confirmed by teslamate MQTT
![{43E00012-7347-4530-A125-AA0CB9165BB1}](https://github.com/user-attachments/assets/09ccbd83-f5cf-4267-9ca9-50a0cf1099a7)

**Comment by speedst3r** [comment]
Separate bug, #6
