### ISSUE TITLE
3Phase bug - Tesla 3

### ISSUE THREAD

**Issue by balgerion** [Haveacry/twc3teslamate#6]
My Model 3 is reporting 2 phase charging via teslamate MQTT - when charging with 3
![{3B3D5630-C380-4233-A003-5AD6506F1C19}](https://github.com/user-attachments/assets/9780a4ff-f4ab-4a8c-aaff-bfd746dc6012)
This is know bug in teslamate. 

Twc3 is reporting only 1 phase chariing
![{50A8C7C9-2968-4C6B-BA32-554DA190ECA8}](https://github.com/user-attachments/assets/b2730692-efe1-4c08-87f6-c1f199dfaebf)

and ofc in evcc charger is "1phase" showing inaccurate data

![{B24A7BEF-3D94-4228-9E38-4CBE00FE07C9}](https://github.com/user-attachments/assets/de22eaa4-3386-4d11-a8c8-139ee424d595)

**Comment by speedst3r** [comment]
Fixed in ac73de7ada88f65c5cac6359d6ce6a4a8f236ec0
